Name - Maahi Sadrani
PRN - 25070123069

In [23]:
# Experiment 09: Study of NumPy library

import numpy as np
a = np.array([1,10,20,30,40,50,500])
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)


[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Dimensions of the given matrix
print(a.ndim)
print(b.ndim)

1
2


In [20]:
# To find the size of the matrix
print(a.size)
print(b.size)

7
9


In [19]:
# To find the shape of the matrix
print(a.shape)
print(b.shape)

(7,)
(3, 3)


In [21]:
# To find the data type of the matrix
print(a.dtype)
print(b.dtype)

int64
int64


In [22]:
# In Buit functons in python
print(np.zeros((2,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#To print identity matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# To arrange a matrix of all alternate numbers
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
# To use the command lin spacce
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [33]:
# Operations on matrix
print(b * 2)
print(a + 5)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[  6  15  25  35  45  55 505]


In [35]:
# Sum
print(np.sum(a))

651


In [36]:
# Median
print(np.median(a))

30.0


In [38]:
# Maximum value
print(np.max(a))

500


In [37]:
# Minimum value
print(np.min(a))

1


In [34]:
# Mean
print(np.mean(a))

93.0
